channels:
  - conda-forge
  - anaconda
dependencies:
  - ipykernel>=6
  - jupyterlab==3.2.9
  - numpy
  - pip
  - git
  - pip:
    - jupyter_contrib_nbextensions
    - jupyterlab-git
    - jupyterlab-link-share
    - pandas
    - matplotlib
    - templater3
